<?php

namespace UserApi\Controllers;

use Cubex\Controller\Controller;
use Packaged\Context\Context;
use Packaged\Http\Response;

class IndexController extends Controller
{

  protected function _generateRoutes()
  {
    return 'index';
  }

  public function getIndex()
  {
    return Response::create(json_encode(['message' => 'index']), 200, ['Content-Type' => 'application/json']);
  }

  public function handle(Context $c): \Symfony\Component\HttpFoundation\Response
  {
    return parent::handle($c); // TODO: Change the autogenerated stub
  }

}